uint64 timestamp # time since system start (microseconds)

uint8 test1
int16 test2
float32 test3
uint8 oil_pre
int8 oil_temp
int8 cyl_coolant_temp1
int8 cyl_coolant_temp2
int8 cyl_coolant_temp3
int8 cyl_coolant_temp4
int16 cyl_exh_temp1
int16 cyl_exh_temp2
int16 cyl_exh_temp3
int16 cyl_exh_temp4
float32 volt_14v
float32 volt_28v
uint32 error_count
float32 voltage
float32 current
float32 temperature
int32 rpm
uint8 power_rating_pct
uint8 esc_index
